/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/englisten/': RouteRecordInfo<'/englisten/', '/englisten', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/033001': RouteRecordInfo<'/posts/033001', '/posts/033001', Record<never, never>, Record<never, never>>,
    '/posts/040401': RouteRecordInfo<'/posts/040401', '/posts/040401', Record<never, never>, Record<never, never>>,
    '/posts/040501': RouteRecordInfo<'/posts/040501', '/posts/040501', Record<never, never>, Record<never, never>>,
    '/posts/baidu-light': RouteRecordInfo<'/posts/baidu-light', '/posts/baidu-light', Record<never, never>, Record<never, never>>,
    '/posts/blender-doc-translation': RouteRecordInfo<'/posts/blender-doc-translation', '/posts/blender-doc-translation', Record<never, never>, Record<never, never>>,
    '/posts/bt-vps-panel-hexo': RouteRecordInfo<'/posts/bt-vps-panel-hexo', '/posts/bt-vps-panel-hexo', Record<never, never>, Record<never, never>>,
    '/posts/coda-build': RouteRecordInfo<'/posts/coda-build', '/posts/coda-build', Record<never, never>, Record<never, never>>,
    '/posts/elwi': RouteRecordInfo<'/posts/elwi', '/posts/elwi', Record<never, never>, Record<never, never>>,
    '/posts/hello': RouteRecordInfo<'/posts/hello', '/posts/hello', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/hugo-github-to-hexo-gitlab': RouteRecordInfo<'/posts/hugo-github-to-hexo-gitlab', '/posts/hugo-github-to-hexo-gitlab', Record<never, never>, Record<never, never>>,
    '/posts/inputnum': RouteRecordInfo<'/posts/inputnum', '/posts/inputnum', Record<never, never>, Record<never, never>>,
    '/posts/js-post': RouteRecordInfo<'/posts/js-post', '/posts/js-post', Record<never, never>, Record<never, never>>,
    '/posts/progressbar': RouteRecordInfo<'/posts/progressbar', '/posts/progressbar', Record<never, never>, Record<never, never>>,
    '/posts/rdp-notes': RouteRecordInfo<'/posts/rdp-notes', '/posts/rdp-notes', Record<never, never>, Record<never, never>>,
    '/posts/rhino2blender': RouteRecordInfo<'/posts/rhino2blender', '/posts/rhino2blender', Record<never, never>, Record<never, never>>,
    '/posts/snap-drop': RouteRecordInfo<'/posts/snap-drop', '/posts/snap-drop', Record<never, never>, Record<never, never>>,
    '/posts/zjj': RouteRecordInfo<'/posts/zjj', '/posts/zjj', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
